name: Programming Fear
description: Blogging about stuffs
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
logo: true
paginate: 5
baseurl: ""
domain_name: "https://programmingfear.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "https://programmingfear.github.io"
author: "Your Name"

# Disqus config
disqus-shortname: ""
