name: ProgrammingFear
description: An open source blog for all genre of programmers.
meta_description: "This is a open source blog for all genre of programmers."
markdown: kramdown
highlighter: rouge
logo: true
paginate: 5
baseurl: "/"
#domain_name: "http://yourblog-domain.com"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "https://programmingfear.github.io"
author: "Your Name"

# Disqus config
disqus-shortname: ""
